<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXH4xgiL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXH4xgiL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXH4xgiL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXH4xgiL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXH4xgiL\App_KernelDevDebugContainer([
    'container.build_hash' => 'XH4xgiL',
    'container.build_id' => '61e606af',
    'container.build_time' => 1666000150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXH4xgiL');
