accueil:
    path: /
    controller: App\Controller\AcceuilController::accueil

deconnexion:
    path: /deconnexion
    controller: App\Controller\AcceuilController::deconnexion

visiteur_historique:
    path: /visiteur/historique
    controller: App\Controller\VisiteurController::historique

visiteur_frais:
    path: /visiteur/frais
    controller: App\Controller\VisiteurController::page_frais

visiteur_login:
    path: /visiteur/login
    controller: App\Controller\VisiteurController::login

visiteur_reception_fiche:
    path: /visiteur/fiche/envoyer
    controller: App\Controller\VisiteurController::reception_fiche



comptable_login:
    path: /comptable/login
    controller: App\Controller\ComptableController::login

comptable_frais:
    path: /comptable/fiches
    controller: App\Controller\ComptableController::fiches
    methods: [GET,POST]